
# username: 您的的用户名(一般是手机号码)
username: "13888888888"

# password: 密码
password: "*****"

# date: 挂号日期,如填写latest自动挂最新一天
date: "2018-01-01"


# hospitalId: 医院id
hospitalId: "162"

# departmentId: 科室id
departmentId: "200002248"

# 关于如何获取 hospitalId 和 departmentId
# 1. 打开挂号页面
# 2. 假设地址栏中地址是 http://www.114yygh.com/dpt/appoint/162-200002248.htm
# 3. 其中 162 是 hospitalId
# 4. 其中 200002248 是 departmentId


# 需要挂早上的号请填写1  需要挂下午的号请填写2
dutyCode: "1"

# patientName: 患者姓名
# 若是自己挂号可为空
patientName: "蔡桓公"

# 就诊卡号
hospitalCardId: ""

# 医保卡号
medicareCardId: ""

# 保险类型
# 1:医保
# 10:自费
reimbursementType: "1"

# doctorName: 医生姓名
# 不填写的话默认选最好的医生
# 填写后若这个医生没有号，会自动选其余号中最好的医生
doctorName: "扁鹊"

#挂号类型是否为儿童号
# 可选项为"true" 或者 "false"
children: "false"

#患儿名字 如果儿童挂号必须填写
childrenName: ""

#患儿证件号 如果儿童挂号必须填写
childrenIdNo: ""

#患儿证件 如果儿童挂号必须填写
#1:身份证
#2:其他
cidType: "1"

# chooseBest: 选择模式
# 不填写的默认从最好的医生开始选择
# 可选项为"yes" 或者 "no"
chooseBest: "yes"

# DebugLevel: 调试等级
# 支持的调试等级有 debug/info/warning/error/critical
DebugLevel: "info"

#使用ios短信和mac电脑接收验证码
# 可选项为"true" 或者 "false"
useIMessage: "false"

# 是否使用 QPython3.6 运行本脚本
# 可选项为"true" 或者 "false"
useQPython3: "true"
